name: Release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        with:
          semantic_version: 25
          extra_plugins: |
            @semantic-release/commit-analyzer@13
            @semantic-release/release-notes-generator@14
            conventional-changelog-conventionalcommits@9
            @semantic-release/changelog@7
            @semantic-release/exec@7
            @semantic-release/git@11
            @semantic-release/github@12
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
